### ISSUE TITLE
Can't login to GitHub

### ISSUE THREAD

**Issue by HisRoyalRedness** [github/VisualStudio#949]
I'm having some trouble logging on to GutHib to push new changes to my repository. I've just recently upgraded to Visual Studio 17. Everything used to work on VS 2015, but doesn't any longer.

- GitHub Extension for Visual Studio  version: 2.2.0.8
- Visual Studio 2017 Professional: Ver 15.0.0+26228.9
- Windows 7 Pro SP1

Detailed steps:
- I have a local clone of a public (personal) repository. I've made changes to the local files
- Staged the changes.
- Attempted to push the changes. 
- The GitHub login dialog appears. I've entered my username and password. I've confirmed that these are correct by logging in to the website.
- I get the following in my ouput pane on Visual Studio

```
Opening repositories:
### Local path, removed the actual path to anonymise ###
Error encountered while pushing to the remote repository: Git failed with a fatal error.
fatal: AggregateException encountered.
   One or more errors occurred.
error: cannot spawn askpass: No such file or directory
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Pushing to https://github.com/### repo path ###.git
```
I have 2 factor enabled on my account.

**Comment by richardmatsu** [comment]
I have a similar problem, but the login fails verifying the 2FA code and never completes the login.

**Comment by shana** [comment]
@HisRoyalRedness is this still happening to you? If it is - the credentials are stored in the Windows Credential Manager, so perhaps something happened that cleared them. Could you open `Credential Manager`, go to `Windows Credentials`, and check the `Generic Credentials` list to see if you have two entries that look like the following:

```
git:https://github.com
https://github.com/
```

Apologies also for the delay in replying, this got missed somehow 😕

**Comment by shana** [comment]
@richardmatsu Could you check the log in `%localappdata%\GitHubVisualStudio\extension.log` and see if you have messages in it that are similar to issue #958?

**Comment by richardmatsu** [comment]
Nope, nothing like that. For kicks, I deleted my saved credentials in Credential Manager but no difference.

2017-04-24 15:09:36.1679|INFO|thread: 1|RepositoryHost|Log in from cache for login '(null)' to host 'https://api.github.com/' FAILED
2017-04-24 15:09:36.1679|INFO|thread: 1|RepositoryHosts|Log in to GitHub.com host 'https://api.github.com/' with username '****' FAILED

**Comment by HisRoyalRedness** [comment]
I've got nothing stored in my Credential Manager. Nothing in the log looks similar to  #958

**Comment by grokys** [comment]
@HisRoyalRedness we're a bit stumped here to be honest. Would it be possible to run Fiddler and take a look at the requests that are being sent?

**Comment by grokys** [comment]
Also, are you still getting these errors?

> error: cannot spawn askpass: No such file or directory
> fatal: could not read Username for 'https://github.com': terminal prompts disabled

These look like low-level errors unrelated to GHfVS. Does your git commandline work?

**Comment by HisRoyalRedness** [comment]
Hi there,

Yes, I still get those errors. I can fetch and pull from the commandline
without any trouble.

I'm working on getting some Fiddler dumps for you

**Comment by HisRoyalRedness** [comment]
OK, perhaps I should have checked this in the first instance ... :-)

It seems that the extension is having some trouble getting through our corporate proxy. I've got the requisite global git entries.

>git config --global --list
http.proxy=127.0.0.1:8088
https.proxy=127.0.0.1:8088

I have CNTLM installed locally to do the NTLM auth through the corporate proxy. Complicated, I know...

`git & other apps --> CNTLM Proxy (127.0.0.1) --> corporate proxy --> web`

I can operate through the command line, so the config must be OK. These same settings appear in the VS git extension (under Repository Settings), and are shown as global settings.

When I attempt to sync my repository through the VS extension, I get the 'cannot spawn askpass' errors, and Fiddler shows auth errors from the corporate proxy. Could it be possible that the extension is ignoring the git proxy settings and picking up the proxy from Internet Options (which would be the corporate proxy)?

**Comment by grokys** [comment]
@HisRoyalRedness did you get any further with this issue? Apologies for not replying earlier, but we were unable to repro here.

**Comment by HisRoyalRedness** [comment]
Yup, still the same behaviour. Generally I stage and commit from Visual Studio, and push and pull to/from remotes from the command line using the standard Git tools. Yes, it's a pain, but I manage to get by with this workflow.

I've since upgraded to a new PC, running Windows 10 (old one was Windows 7), upgraded to Visual Studio 2017, and I still get the exact same error from Git (i.e. error: cannot spawn askpass).

Git command line works fine.

**Comment by MuqadderIqbal** [comment]
Hey guys - just landed on this page trying to search for this same issue (VS2017, behind corp firewall but with correct HTTP and HTTPS proxies set in my environment variables). I am able to use Git add-in for VS2017 to connect to my GitHub account and clone my repositories but when I try to push a change via VS Git add-in, I get the same error as HisRoyalRedness (cool username btw ;)). 
Any luck establishing a root cause and/or a fix/workaround?

**Comment by grokys** [comment]
@HisRoyalRedness @MuqadderIqbal so the problem occurs when pushing/pulling from team explorer? Are you able to log into GitHub using the Team Explorer "Connect" section, as described here?

https://github.com/github/VisualStudio/blob/master/docs/getting-started/authenticating-to-github.md

**Comment by MuqadderIqbal** [comment]
@grokys I am able to successfully connect to my GitHub repo and authenticate. I am also able to successfully clone my library. However, after committing a change, an attempt to push it to GitHub repo results in an error. Here is the error stack trace:-

Opening repositories:
C:\MyGithub\Learn-Pandas
Commit dea72b81 created locally in repository C:\MyGithub\Learn-Pandas
Error encountered while pushing to the remote repository: Git failed with a fatal error.
HttpRequestException encountered.
   An error occurred while sending the request.
cannot spawn askpass: No such file or directory
could not read Username for 'https://github.com': terminal prompts disabled
Pushing to https://github.com/MuqadderIqbal/Learn-Pandas.git

**Comment by HisRoyalRedness** [comment]
@grokys Ditto for me. I can connect and authenticate to GitHub. I can see the list of my repositories from within Visual Studio. Just can't push or pull. My error message is a little different. This was after attempting a pull
```
Git failed with a fatal error.
fatal: TaskCanceledException encountered.
   A task was canceled.
error: cannot spawn askpass: No such file or directory
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

And this after a push:
```
Opening repositories:
C:\Users\KeithF\Source\Repos\HBusLogger
Commit b85c226f created locally in repository C:\Users\KeithF\Source\Repos\HBusLogger
Error encountered while pushing to the remote repository: Git failed with a fatal error.
fatal: TaskCanceledException encountered.
   A task was canceled.
error: cannot spawn askpass: No such file or directory
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Pushing to https://github.com/HisRoyalRedness/HBusLogger
```

If I push from a command prompt (just the standard Windows cmd, not git bash), I'm asked to enter my user name and password, and the push succeeds
```
C:\Users\KeithF\Source\Repos\HBusLogger>git push
fatal: TaskCanceledException encountered.
   A task was canceled.
Username for 'https://github.com': HisRoyalRedness
Password for 'https://HisRoyalRedness@github.com':
Counting objects: 22, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (22/22), done.
Writing objects: 100% (22/22), 2.93 KiB | 1.46 MiB/s, done.
Total 22 (delta 18), reused 0 (delta 0)
remote: Resolving deltas: 100% (18/18), completed with 6 local objects.
To https://github.com/HisRoyalRedness/HBusLogger
   92d8346..b85c226  master -> master
```

**Comment by HisRoyalRedness** [comment]
OK, I've got it working now. I thought I'd try get some Fiddler traces for you, couldn't get it to work through Fiddler (with the complex arrrangement of corporate proxies and my local CNTLM proxy, its no wonder), and then put it all back together again. Then hey presto, it all just worked!

So, I'm guessing that I got one of these steps wrong at some point. Anyway, this is what I did

- Verified that CNTLM was configured correctly. Other apps use this, so I was certain it was set up correctly. I've got CNTLM accepting connections at 127.0.0.1:8088, and passing them on to the corporate proxy with the appropriate Window logon details.
- Set global proxy settings. I had repository and global settings applied. I've removed the repository settings and it seems to work with just the global ones (as it should)
  - `git config --global http.proxy `http://127.0.0.1:8088` 
  - `git config --global https.proxy `https://127.0.0.1:8088` 
- Confirmed that the config file at `%USERPROFILE%\.gitconfig` had the correct settings. I can't remember if it did or not. I did edit the file while trying to get Fiddler working
- Created the HTTP_PROXY and HTTPS_PROXY environment variables. Something required them. Not sure if it was the Visual Studio Github extension or something else

I can now push and pull from my repository

I've got a sneaky suspicion that I configured my https proxy setting with an http url. I did notice this when messing with the settings and corrected it. I've since set it back to http to see if I could get it to fail again, but was unsuccessful. Something to check anyway if you still have problems

Hopefully it all continues to work. I'll post an update in a day or two.

**Comment by grokys** [comment]
Glad you got it working @HisRoyalRedness. As I suspected, it was a proxy issue. Does the information above help you @MuqadderIqbal?

One thing to note is that GitHub for Visual Studio doesn't actually supply the git push and pull functionality - this is part of Team Explorer, so if the login works then the problem was actually on Microsoft's side.

I'm going to close this issue now as it looks like there's a fix and it's also not actually our functionality that's exhibiting the problem.

**Comment by vCillusion** [comment]
I faced the same issue guys, it appears when I have only TLS1.2 enabled on my PC. After enabling TLS 1.1, SSL.x the issue was resolved. For enabling and disabling I used IISCrypto software. Hope that helps the team and other users.

**Comment by grokys** [comment]
Thanks for letting us know @vCillusion - that will be helpful information for anyone experiencing this problem in future. Looks like we might need to look into why this is the case, maybe we can fix it on our end. I've opened an issue to track this over in #1443.

**Comment by pbenitez** [comment]
Thanks @HisRoyalRedness
My email was wrong in here %USERPROFILE%\.gitconfig
Corrected and now is working like a charm.

**Comment by davidehnis** [comment]
I've tried most of the suggestion list above.  I am still not able to Push.  Here is the output from the extension.log:

2016-09-28 19:38:48.3619|INFO|thread: 1|RepositoryHost|Log in from cache for login 'davidehnis' to host 'https://api.github.com/' SUCCEEDED
2016-09-28 19:38:48.3799|INFO|thread: 1|RepositoryHosts|Log in to GitHub.com host 'https://api.github.com/' with username 'davidehnis' SUCCEEDED
2016-09-28 19:39:39.7486|ERROR|thread:75|PullRequestCreationViewModel|Octokit.ApiValidationException: Validation Failed
   at Octokit.Connection.HandleErrors(IResponse response) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 562
   at Octokit.Connection.<RunRequest>d__52.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 543
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__51`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 528
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Post>d__21`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\ApiConnection.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.ExceptionHelpers.ThrowIfNotNull(Exception exception)
   at System.Reactive.Subjects.AsyncSubject`1.GetResult()
   at GitHub.Services.PullRequestService.<PushAndCreatePR>d__8.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.App\Services\PullRequestService.cs:line 93
{"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"A pull request already exists for davidehnis:Create-initial-constructs."}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
2016-09-28 19:42:47.6679|ERROR|thread:53|PullRequestCreationViewModel|Octokit.ApiValidationException: Validation Failed
   at Octokit.Connection.HandleErrors(IResponse response) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 562
   at Octokit.Connection.<RunRequest>d__52.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 543
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__51`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 528
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Post>d__21`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\ApiConnection.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.ExceptionHelpers.ThrowIfNotNull(Exception exception)
   at System.Reactive.Subjects.AsyncSubject`1.GetResult()
   at GitHub.Services.PullRequestService.<PushAndCreatePR>d__8.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.App\Services\PullRequestService.cs:line 93
{"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"No commits between master and Create-initial-constructs"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}

**Comment by vdms-mark** [comment]
Hi, I was getting the same error as the original poster (when fetching)
> error: cannot spawn askpass: No such file or directory
fatal: could not read Username for 'https://github.com': terminal prompts disabled

I just reverted my GitHub extension (from 2.4.2.1331 to 2.2.0.10) and I am no longer getting those errors.

**Comment by rafaelsc** [comment]
I Just start getting this erros too. Only resolve to after force a logoff/login in GitHub Desktop.

**Comment by grokys** [comment]
@davidehnis thanks for the logs. I can't see anything in there except creating pull requests failing because of a PR already existing for the branch and then a branch not having any commits.

How were you trying to push? Was it from `Team Explorer -> Sync`? If so, that's part of Team Explorer and so not our extension which would explain the lack of logs. Do you think you could:

1. Post a screenshot of the error, given that there's nothing in the logs
2. Try pushing from the command line

This may help us diagnose the problem.

**Comment by grokys** [comment]
> Hi, I was getting the same error as the original poster (when fetching)
>> error: cannot spawn askpass: No such file or directory
>> fatal: could not read Username for 'https://github.com': terminal prompts disabled
> I just reverted my GitHub extension (from 2.4.2.1331 to 2.2.0.10) and I am no longer getting those errors.

Thanks for the information @vdms-mark. It's strange that reverting the GitHub extension fixed this, because as far as I can tell, this isn't happening in our code. Would you be able to upgrade back to the latest version of GitHub for Visual Studio again and see what happens? I suspect that reverting the extension might just have caused Visual Studio to fix itself...

**Comment by grokys** [comment]
> I Just start getting this erros too. Only resolve to after force a logoff/login in GitHub Desktop.

Again, strange @rafaelsc - we shouldn't be sharing credentials with GitHub Desktop... I'm trying to work out how these separate issues and solutions fit together.

**Comment by grokys** [comment]
I've just come across this problem myself, and thought I'd document the cause here in case anyone else is experiencing this problem. Trying to push to a repository was showing the following error in the output pane:

```
error: cannot spawn askpass: No such file or directory
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

There were two causes for this:

1. I was not already logged in via GitHub for Visual Studio
2. I entered my password incorrectly

Lets look at these in detail:

## I was not logged in via GitHub for Visual Studio

The following dialog was being shown:

![image](https://user-images.githubusercontent.com/1775141/36424904-3fdce798-1645-11e8-9c09-55ff50a785ca.png)

**Important: This is not part of GitHub for Visual Studio, this is part of the [Git Credential Manager for Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows). _If you are seeing this dialog you are not signing in using GitHub for Visual Studio._ Close the dialog and [log in using GitHub for Visual Studio](https://github.com/github/VisualStudio/blob/master/docs/getting-started/authenticating-to-github.md)**.

## I entered my password incorrectly

In the above dialog, I entered my password incorrectly. When this happens, the Git Credential Manager for Windows tries to ask you for your password on the command-line. Because we're not running on the command line this fails with `error: cannot spawn askpass: No such file or directory`, which is a very unhelpful error message.

This error might not be caused by entering you password incorrectly - it could be caused by proxy settings etc. The fact remains, I was not signing in using GitHub for Visual Studio: instead you should [log in using GitHub for Visual Studio](https://github.com/github/VisualStudio/blob/master/docs/getting-started/authenticating-to-github.md)

**Comment by Barsonax** [comment]
This is still happening to me even though iam logged in. Gonna remove 2FA I guess......

**Comment by twixwix** [comment]
I have the same issue without 2FA.... grrrrr

**Comment by nimad** [comment]
I ran into this today. Updated to build 15.5.7 and the problem went away

**Comment by meaghanlewis** [comment]
Hey @Barsonax and @twixwix, hopefully updating VS to 15.5.7 will fix your login problems.

**Comment by Barsonax** [comment]
Yes it does!

**Comment by sergiobarriel** [comment]
As @nimad says, if you update Visual Studio, it works

**Comment by dankoster** [comment]
Visual Studio Enterprise build 15.5.7 also fixed the issue for me. 
Also updated to the latest version of the GitHub extension.

**Comment by MkazemAkhgary** [comment]
I ran to this problem just now. what just happened? 😄 🤔

**Comment by skarletlightning** [comment]
Same as above, updating to 15.5.7 fixes this.

**Comment by nkev** [comment]
This sucks. It was working yesterday and suddenly not today. I don't have a spare hour right now to do a VS install. I'm really getting sick of all this MS BS.

**Comment by shiftkey** [comment]
Please ensure you're running VS 15.5.7 as there are some updates related to [disabling weak cryptography](https://githubengineering.com/crypto-removal-notice/) that were rolled out today.

**Comment by chris-githu** [comment]
Updating to 15.5.7 fixed this.
Thanks.

**Comment by AOS-Miracle** [comment]
Updating to VS 15.5.7 helped me and a colleague this morning! 
We both had the "HttpRequestException"-version of the issue. Updating solved it immediately.
Thanks to everybody who spend their time helping to find a solution.

**Comment by pablodelolmo** [comment]
Yes, the update fixed this.

**Comment by mvinicius85** [comment]
Updating solve it here too.

**Comment by ytian2** [comment]
Updating also fixed it here, thanks.

**Comment by rfustino** [comment]
15.7 is a winner!

**Comment by gojimmypi** [comment]
thank you @meaghanlewis and @nimad  !! GitHub was working just recently with 15.5.6 - the update today to 15.5.7 helped tremendously for the `error: cannot spawn askpass: No such file or directory `message today!

**Comment by lloydjatkinson** [comment]
In the future regarding **breaking changes** a better error message along the lines of `security settings invalid` would be better instead of `cannot spawn askpass: No such file or directory` which caused me to spend wasted time trying to debug what I assumed to be a corrupted install (because since when do executable suddenly vanish normally?).

**Comment by avelis26** [comment]
I see this issue is closed but I am experiencing exactly this issue.

I'm running VS17.5, everything has been working completely fine for 3 months and all of a sudden yesterday with zero changes, I tried to push and I get the error:

> Error encountered while pushing to the remote repository: Git failed with a fatal error.
> fatal: HttpRequestException encountered.
>    An error occurred while sending the request.
> error: cannot spawn askpass: No such file or directory
> fatal: could not read Username for 'https://github.com': terminal prompts disabled
> Pushing to https://github.com/<user>/<repo>.git

And yes, push / pull is working fine from the command line and even pull is working in VS ... just not push.

**Comment by gojimmypi** [comment]
@avelis26 update to 15.5.7 to fix

**Comment by avelis26** [comment]
I saw that and thanks... that worked.

**Comment by ststeiger** [comment]
-1: No admin rights - cannot install any updates...  should work - no sysadmin wide and far - fucked ...

**Comment by austinindiedev** [comment]
Thanks @nimad, updating my VS worked.

**Comment by bollafa** [comment]
Thanks everybody! Now it works!

**Comment by NobleKiss** [comment]
I Work To 2:00 AM，Tell me ，because version Question ? what?????

**Comment by Ashwin-Deshmukh-REISystems** [comment]
updating VS to 15.5.7 worked!!

**Comment by rdefulio** [comment]
The issue here is that Visual Studio bundles their own git.exe and (based on the above comments) the version prior to 15.5.7 was a piece of junk.  I have git 2.16-x64 installed so I don't need their version.    The fix for me (without updating to 15.5.7) was to delete this folder --

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git`

**Comment by rdefulio** [comment]
Followup on my previous post ...  If you can't install the update right now.. 

GoodGit = `C:\Program Files\Git`
BadGit = `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git`

BadGit is found first by visual studio, unless you edit your visual studio options and remove the CommonExtension folder from the search path.  

```
[C:\]dir git.exe /s/b/a
C:\Program Files\Git\bin\git.exe
C:\Program Files\Git\cmd\git.exe
C:\Program Files\Git\mingw64\bin\git.exe
C:\Program Files\Git\mingw64\libexec\git-core\git.exe
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\cmd\git.exe
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin\git.exe
```

After deleting the bad git folder, make sure running git.exe from the command prompt finds the correct version via the system path.

```
[C:\]git --version
git version 2.16.2.windows.1
```

**Comment by AlexanderJ-ULabs** [comment]
This issue was fixed for me by updating to the latest 15.5.7 and installing the Git For Visual Studio extension again.

**Comment by StingyJack** [comment]
> Because we're not running on the command line this fails with error: cannot spawn askpass: No such file or directory, which is a very unhelpful error message.

Also in this department of unhelpful error messages, I love that this reports the exception type name instead of the exception message, stack trace, or something actually meaningful....  "AggregateException encountered" =<

**Comment by ststeiger** [comment]
@StingyJack: That's all the info you get on the command line. No stack trace. And yes, the error message is very unhelpful. That has something to do with the programmer, though, not the reporter.

**Comment by grokys** [comment]
> Also in this department of unhelpful error messages, I love that this reports the exception type name instead of the exception message, stack trace, or something actually meaningful.... "AggregateException encountered" 

Yes I agree, the error message is not helpful. I'm tagging some of the Team Explorer people here so they're aware of this thread: @kaylangan @clboles @jeremyepling 

Thanks for everyone's input on this!

**Comment by benmccallum** [comment]
Could commit but couldn't push. Upgraded Git for Visual Studio and didn't help. Then upgraded to VS 15.5.7 and it worked again.

**Comment by JonathanERoss** [comment]
I was having the same problem.  Upgraded to VS 15.5.7 and it worked again.

**Comment by vivienchevallier** [comment]
Upgrading to VS 15.5.7 also solved the problem for me.

**Comment by AnuragLalithambikai** [comment]
I was facing the same issue on both VS2017 and GIT Bash. Upgrading to VS 15.5.7 has fixed both. Thanks all.

**Comment by nkev** [comment]
Upgrading to VS 15.5.7 fixed it last week. Now the same error is back. Now what? Geez I hate how much time Visual Studio wastes. It's the opposite of what it's supposed to do!

> Error encountered while fetching: Git failed with a fatal error.
TaskCanceledException encountered.
   A task was canceled.
cannot spawn askpass: No such file or directory
could not read Password for 'https://mylogin@github.com': terminal prompts disabled

**Comment by benmccallum** [comment]
@nkev, there was a Git extension for VS update I saw last night, wonder what that was for. Anddoes it update Git credential manager under the covers...? Will see if mine is broken today after updating the ext last night :p

**Comment by lmoxiel** [comment]
Fixed for me as well by upgrading VS2017
Old Version: 15.5.2
New Version: 15.6.2

Also note in the 15.6 release they've added more Git support:
"We added support for Git authentication over SSH. You can configure continuous delivery for solutions under source control in a VSTS or GitHub Git repo with SSH AUTH enabled."

https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#15.6.2

**Comment by nkev** [comment]
It's silly that we have to update the whole VS for incremental updates. It takes half an hour on my machine and I'm reluctant to do it for every release.

**Comment by shtse8** [comment]
I have the same issue, now can i fix it without reinstall anything?

**Comment by grokys** [comment]
@shtse8 you don't have to reinstall, you just need to update Visual Studio.

**Comment by Wallonman** [comment]
Upgrade VS from 15.3.3 to 15.6.4 -> now able to push to github !

**Comment by chrisgel15** [comment]
Updating Visual Studio did the trick for me too!

**Comment by SanjibKHarchowdhury** [comment]
I have VS 2017 version 15.6.4, GitHub.VisualStudio version 2.4.3.17 and GitBash version 2.16.1.windows.4 I am facing the same issue while trying to pull using VSTS Git Hub extension.

I am behind corporate proxy, configured through CNTLM, I verified git config --global, the correct proxy address is configured for http and https.

While logging in VSTS does ask username, password and 2 factor authentication code then connects, then when trying to pull it shows the following exception in VS output window, can anyone please help

Git failed with a fatal error.
HttpRequestException encountered.
   An error occurred while sending the request.
cannot spawn /C/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/mingw32/libexec/git-core/git-askpass.exe: No such file or directory
could not read Username for 'https://github.com': terminal prompts disabled

**Comment by aperwe** [comment]
I had the same problem. After updating to the latest VS, problem is fixed. Still, error message is really confusing.

**Comment by Maximres** [comment]
Try to set username and password to your Remote url in repository settings.
Remotes: https://**username:pass**@github.com/Username/Repo

**Comment by cactusoft** [comment]
I had same issue. In my case for some reason on my laptop, when I have my VPN on, no Windows universal type apps can connect to the internet. Edge for example cannot, while chrome and Firefox run fine. Same deal with Windows weather and news apps. Curiously, the live tiles can still update, but opening the app it says no connection.

It seems this part of Visual Studio must use similar code, because when I turned my VPN off, it works fine.

I use the same VPN account and credentials on my desktop machine, and it works fine - same version of Windows 10, too. This issue is something to do with windows. At some point a Windows 10 major update fixed it, but then it got broken again.

**Comment by Fieel** [comment]
Had the same issue and noticed i didn't update in a while. 

Update Visual Studio and now it works. Thanks.

**Comment by Pritchard** [comment]
Broken for me still in 15.4.7

```
Error: cannot spawn /C/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/mingw32/libexec/git-core/git-askpass.exe: No such file or directory
Error encountered while pushing to the remote repository: Git failed with a fatal error.
could not read Password for 'https://blahblahblah@bitbucket.org': terminal prompts disabled
Pushing to https://blahblahblah@bitbucket.org/blahblahblah/blahblahblah.git
```

This is still the case even though recent versions of Visual Studio have apparently solved the issue: https://github.com/github/VisualStudio/issues/949

I have tried clearing all credentials from Windows credentials manager, but they do not appear to be getting recreated into the credentials manager when I sign back into Atlassian.

I cannot find any GitCredentialsManager directory on my system, even though I have enabled the display and search of hidden files and system directories, so no tenant.cache file that I can delete to try and resolve, either.

Have executed git config and am not seeing any proxies, although I am running Windows from a Parallels VM. Any other internet connectivity is working fine though, including auth... credentials just aren't getting stored. No enterprise network settings on my machine, etc. again, two-factor auth was working not too long ago.

**Comment by pddring** [comment]
I've got Visual Studio 2017 v15.7.4 installed in a school for my students to use git to manage their projects. I've got the GitHub for VS plugin version 2.5.3.2888. Cloning, committing and pushing all works fine for 'normal' GitHub repos but fails when using the private organisation account that I need for school assessments.

Here's the error:

```
Error encountered while cloning the remote repository: Git failed with a fatal error.
ArgumentNullException encountered.
   Value cannot be null.
Parameter name: path
cannot spawn /C/Program Files/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/mingw32/libexec/git-core/git-askpass.exe: No such file or directory
could not read Username for 'https://github.com': terminal prompts disabled
```

**Comment by meaghanlewis** [comment]
@Pritchard @pddring can you update to Visual Studio 2017 v15.7.5 and let us know if you continue to have problems?

**Comment by bwlegalana** [comment]
@meaghanlewis  I am having same issue and error as @pddring  with  Visual Studio 2017 v15.7.5

I can fetch a brand new branch and connect to a repository, however unable to fetch/push commits

**Comment by Pritchard** [comment]
We started having the same problem with Atlassian's own software SourceTree with BitBucket HTTPS repos. We've quickly moved our teams to use SSL repo URLs only from hereon. This is resolving the issue across all teams, even those which are not using Visual Studio.

**Comment by spookiecookie** [comment]
@Maximres  Your solution (https://github.com/github/VisualStudio/issues/949#issuecomment-386886010) worked for me. Nothing else before worked. :)

**Comment by JedatKinports** [comment]
This started here after I have updated Visual Studio to version 15.7.6. I cleared my bitbucket credentials and re-entered them but the results is still the same. :(

**Comment by TymekMM** [comment]
Git integration with VS not working anymore.
Only command line tools.
Any action to git from VS - problems with credentials.
Any action from command line working as should.
What else can Microshit destroy  ?

**Comment by SimonSDA** [comment]
Same as the above 2 - another VS update (15.7.6) and git integration broken yet again. Can push via command line but not in VS. I can do fetches ok, but not push. Very frustrating!

Error encountered while pushing to the remote repository: Git failed with a fatal error.
HttpRequestException encountered.
   An error occurred while sending the request.
cannot spawn /C/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/mingw32/libexec/git-core/git-askpass.exe: No such file or directory
could not read Password for https://xyz : terminal prompts disabled
pushing to https://xyz

**Comment by grokys** [comment]
If you're unable to push, this is a problem with Team Explorer's git integration rather than GitHub for Visual Studio. @clboles @kaylangan @jeremyepling any idea?

**Comment by TymekMM** [comment]
Use command line, everything working fine.

**Comment by AmosHason** [comment]
It has started to happen to us as well out of nowhere with no changes in the environment at all. Git with VS doesn't work, but git in command line works fine. The solution of hard-coding the password in the remote settings (https://github.com/github/VisualStudio/issues/949#issuecomment-386886010) fix this issue, but it's very insecure to store a password in plain text like this.

**Comment by whoisj** [comment]
@SimonSDA @AmosHason @TymekMM @richardmatsu JedatKinports could check your local disk and determine if "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\libexec\git-core\git-askpass.exe" actually exists or not?

I'm trying to determine if this is a Visual Studio installer issue or something else. Thanks! 🙇

**Comment by AmosHason** [comment]
@whoisj It does exist.

I actually gave up and configured SSH key authentication, and now Git works with VS without any issues.

**Comment by GarrettDavis** [comment]
I just upgraded to 15.7.6 and I'm having the same issue. Configured SSH key authentication, but Visual Studio integration still not working. The "git-askpass.exe" does indeed exist at the path mentioned in the error message as not existing.

@whoisj Any other ideas?

**Comment by whoisj** [comment]
To those who are having this issue, capturing additional trace logs would be very useful towards discovering the root cause and resolving the issue. To enable tracing...

1. Open Command Prompt
2. Run `setx GIT_TRACE %UserProfile%\git.log`.
3. Run `setx GCM_TRACE %UserProfile%\git.log`.
4. Restart all Git clients including consoles, Visual Studio, etc.
5. Reproduce the issue.
6. Collect the logs from `%UserProfile%\git.log`.

Once you have the logs captured, please share them here. Of course, as always, please [redact](https://www.dictionary.com/browse/redact) any personal, secret, or personally identifiable information before sharing on the Internet.

Of time the logs will get large. To avoid this, you can disable trace logging by...

1. Open Command Prompt
2. Run `setx GIT_TRACE ""`.
3. Run `setx GCM_TRACE ""`.
4. Restart all Git clients including consoles, Visual Studio, etc.

**Comment by SimplerSoftware** [comment]
Running into this issue as well with the new update to VS :(

**Comment by ligiasilvamendes** [comment]
Same problem here... Trying to pull/push bitbucket updates on Visual Studio Version 15.7.6.

**Comment by PradoRodrigo** [comment]
I'm having the same problem using bitbucket and Visual Studio Version 15.7.6.

**Comment by lucas-moura** [comment]
Same problem here. I had to pull/push commis out VS. My VS version 15.7.6 too. T.T

**Comment by qicaro** [comment]
Can't pull and push either. Before today it were working fine, now when I try to pull or push I get this error message:
No such file or directory could not read Username for 'https://bitbucket.org': terminal prompts disabled

**Comment by Monte-Christo** [comment]
This is definitely related to the VS 15.7.6 update. I was able to push and pull yesterday, then updated VS, now no go. Identical behavior at work. The file itself (git-askpass.exe) does exist.

**Comment by whoisj** [comment]
Thanks for that trace log @GarrettDavis. The root error message there is `The underlying connection was closed: The connection was closed unexpectedly.` This message is being reported by [Git Credential Manager for Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows).

All, we saw error message like this when [GitHub deprecated support for TLS1.0 and TLS1.1](https://githubengineering.com/crypto-deprecation-notice/). I have no idea, though I will try to find out, if Atlassian has done something similar. In the meantime you can reference this [Developer Community topic](https://developercommunity.visualstudio.com/content/problem/201457/unable-to-connect-to-github-due-to-tls-12-only-cha.html) to potentially find workarounds for your current situation.

**Comment by ivleth** [comment]
but for now, going ssh is the only option besides using command line git commands? Reinstalling Visual studio is pretty cumbersome...

**Comment by grokys** [comment]
> The cannot spawn /C/Program Files (x86)/.../git-askpass.exe: No such file or directory message is a symptom of credential acquisition failing unexpectedly.

@whoisj I know this is probably easier said than done, but would it be possible to display a more helpful error message when such things fail? `cannot spawn /C/Program Files (x86)/.../git-askpass.exe` isn't just unhelpful, it's misleading...

**Comment by JedatKinports** [comment]
@whoisj yes. The file git-askpass.exe does exist in "\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\libexec\git-core".

**Comment by rolandh** [comment]
I just updated to 15.8.0 Preview 5.0 and it broke git causing this error message.

> HttpRequestException encountered. An error occurred while sending the request. cannot spawn /c/program files (x86)/microsoft visual studio/preview/enterprise/common7/ide/commonextensions/microsoft/teamfoundation/team explorer/Git/mingw32/libexec/git-core/git-askpass.exe: No such file or directory could not read Username for 'https://bitbucket.org': terminal prompts disabled

15.7.2 which I also have installed has no problem doing a push from the same .sln file.

Any suggestions?

**Comment by Monte-Christo** [comment]
I am using SourceTree or git bash to do my pushing and pulling while VS 2017 refuses to sync. Tortoise Git  or any other Git client would work as well, I guess. In my case, only syncing to BitBucket is broken. GitHub repos sync just fine.

**Comment by AmosHason** [comment]
Have a look [here](https://stackoverflow.com/questions/51725278/extension-for-visual-studio-unknown-error-unable-to-push-or-fetch-anything).

**Comment by KevinRamharak** [comment]
So  i ran into this error and it seems that the bundled Git-Credential-Manager-for-Windows/ in VIsual Studio 2017 is not of the latest release yet. Downloading the latest release and putting it on top of the files in VIsual Studio 2017 worked for me.

```
1. download the zip file gcmw-v1.17.0.zip from https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases
2. navigate to C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\libexec\ (or wherever your 'missing' git-askpass.exe resides).
3. make a copy of the git-core folder and rename it backup or something like that
4. put the files from the zip file on top of the contents of your new git-core folder and overwrite where prompted
```
Let me know if this works for you

**Comment by lucas-moura** [comment]
@KevinRamharak it's working, thanks!

**Comment by vlardn** [comment]
For me workaround by @KevinRamharak with overwriting Git-Credential-Manager-for-Windows with latest version didn't worked until I've removed "login" from remote settings (i.e changed https://login@bitbucket.org/myrepo/myproject.git to https://bitbucket.org/myrepo/myproject.git) and also started to use Atlassian ID with full email.

**Comment by TymekMM** [comment]
@whoisj I did confirm it few posts earlier. File is there, seating there in proper warm corner and making nest

**Comment by Monte-Christo** [comment]
@KevinRamharak  Works like a charm. Thanks. I had installed latest Git-Credential-Manager-for-Windows earlier, but only manually overwriting the files fixed the issue for me.

**Comment by DoumaWebDesign** [comment]
@KevinRamharak - awesome - fix worked! thanks!

**Comment by samuelalvin** [comment]
For me, I did overwrite Git-Credential-Manager-for-Windows with the latest version just as what @KevinRamharak said. But then I need to go to Control Panel > Credential Manager, and directly input my username and password there for the login to work.

**Comment by rafalowski** [comment]
@KevinRamharak - You are a life saver!!!! fix worked thanks!

**Comment by willandus** [comment]
@KevinRamharak - Big thanks for your help! It's working!

**Comment by whoisj** [comment]
Hello everybody. I'd like to announce [GCM v1.17.1 Preview 1](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/milestone/29) is available for download. While this won't directly fix the issue with Visual Studio being able to authentication successfully with BitBucket, it should unblock you if you...

1. Download and install the tool
2. Use Git for Windows to interact with your BitBucket repository in a way that forces it to authenticate
3. Logon using the Atlassian provided BitBucket interface.

Once you've done this, your credentials will be cached in the Windows Credential Manager, and Visual Studio should have access to them. Please, let me know how this goes and best of luck.

PS.
Yes, we're still working towards a more permanent solution but I wanted to provide a possible work around as early as possible.

**Comment by joef12345** [comment]
Just installed V1.17.1 preview 1 and it solved my auth problem.  Thanks!

**Comment by GoodGun** [comment]
@whoisj not worked installing GCM v1.17.1 Preview 1 ,but after downloading the source with .zip file then i applied manually @KevinRamharak suggestion then works for me.

**Comment by JedatKinports** [comment]
@whoisj it didn't work with the .exe file. But when I have downloaded the .zip file and manually copied the files into \Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\libexec\git-core it worked. Thanks @KevinRamharak and @whoisj !

**Comment by qicaro** [comment]
#MicrosoftShouldHireKevin

**Comment by willandus** [comment]
@whoisj It's ok. Copy the content of gcmw-v1.17.1-preview.1.zip to c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\libexec\git-core\ dir, and it solved my auth problem.
The problem was same on Win7 and Win10, but @KevinRamharak suggestion only work on Win7.
Thanks!

**Comment by qicaro** [comment]
@willandus My problem was in win10 and works fine for me.

**Comment by JoeHz** [comment]
This sure taught me not to get the latest updates for Viz-Studio...

**Comment by ststeiger** [comment]
The 2018-EAP comes with publishing feature & experimental Blazor support.

**Comment by causa-prima** [comment]
@KevinRamharak it's working, thanks!

**Comment by plcnut** [comment]
@KevinRamharak Thank you! This got me back up and running.

**Comment by varzaman** [comment]
Just wanted to mention that what KevinRamharak said worked for me as well!

**Comment by mpalladinru** [comment]
Latest update 15.8 broke it again

**Comment by JoeHz** [comment]
@mpalladinru It was the one before 15.8 that first broke it for me. I'm assuming that meant you had it fixed manually somehow and it overwrote it?

**Comment by rolandh** [comment]
Make sure to use this path if you are using the preview of VS

> C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\libexec\git-core

**Comment by willandus** [comment]
The latest VS update (15.8) broke it again.
I'm just copy the content of gcmw-v1.17.1-preview.1.zip to c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\libexec\git-core\ but it was not enough. Then overwrite the content of the directory above with @KevinRamharak 's suggestion. The content of gcmw-v1.17.0.zip was solved the atuh problem for me.

**Comment by mpalladinru** [comment]
@JoeHz yes, I unpacked archive contents and it was working until yesterday, when update arrived. So I unpacked archive contents again and it working again now

**Comment by FabricioAraujoRJ** [comment]
Still broken in 15.8.1

**Comment by grokys** [comment]
@whoisj just wanted to say that this problem seems to be escalating, we've had more reports of the same problem over at #1531.

**Comment by whoisj** [comment]
@grokys and everyone else, we (Microsoft) have worked closely with Atlassian to resolve the Bitbucket authentication issue. I personally (with the blessing of our gate keepers) have pushed the fix into Visual Studio, and an update will arriving as soon as the release gears can complete their turning. I, personally, do not have much insight into the timing of VS update releases, but I know we're targeting 15.8 and 15.9 (still in preview) with the fix. __I do not know the exact timing__ but I do not think it'll be very long.

I do apologize for missing the 15.8.1 release train. The fix just wasn't ready by the time the train had "left the station" and I still had to complete the steps of pulling the fixes into VS, and validating them (not just to fix Bitbucket, but also to ensure they _did not break anything else_ 😲 - they don't 🙂).

So the best I can do right now is say "hold tight" the fix is incoming - promise!



Oh, and I am very sorry that we let this issue slip past. We did not have robust validation around Bitbucket authentication previously. We now have better validation, and will continue to improve all of our testing over time. Again, very sorry and the fix exists, it is on its way, and should be available soon (for some definition of soon).

**Comment by koenj** [comment]
disclaimer: slightly off topic.

Since last night, we start seeing the same issue on VSTS:
`fatal: could not read Username for 'https://bitbucket.org': terminal prompts disabled`

This started after the fix for the [Hosted Agent Issues in West Europe](https://blogs.msdn.microsoft.com/vsoservice/?p=17335) (not sure if this is related).

Could you provide some insight on what we can do in VSTS to work around this issue,?

Thanks!

**Comment by whoisj** [comment]
Until VS is patched, [this suggestion](https://github.com/github/VisualStudio/issues/949#issuecomment-411349635) is the only one I know for sure that will help. This is because we increased the HTTP_TIMEOUT significantly as part of the work-around for Bitbucket before we understood the root cause. The time change stuck because it would help in other areas.

**Comment by koen12h51** [comment]
Thanks for the input;

I opened a support request with Microsoft for the VSTS bug;
they have released a patch to VSTS in the meantime, fixing my issue.
So on VSTS, everything is working fine again.

**Comment by PrasanthMahendrakar** [comment]
Updated to version VS 15.8.2, still facing the same issue.
Error encountered while fetching: Git failed with a fatal error.
HttpRequestException encountered.
   An error occurred while sending the request.
cannot spawn /c/program files (x86)/microsoft visual studio/2017/professional/common7/ide/commonextensions/microsoft/teamfoundation/team explorer/Git/mingw32/libexec/git-core/git-askpass.exe: No such file or directory
could not read Username for 'https:xxxx.com': terminal prompts disabled

**Comment by JoeHz** [comment]
I'm now able to push to bitbucket with 15.8.2

**Comment by JedatKinports** [comment]
15.8.2 fixed it for me. Thanks!

**Comment by wiswis15** [comment]
i was also struggeling with it . Updated VS to 15.8.9 and he issue was fixed .

**Comment by samconn** [comment]
I updated to VS 15.9.3 and the problem returned!!!

Overwriting the 'refreshed' git-core assemblies with those from https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/v1.18.2 fixed the problem.

**Comment by Grauenwolf** [comment]
Same for me.

**Comment by Manika-Kumari** [comment]
> 
> 
> So i ran into this error and it seems that the bundled Git-Credential-Manager-for-Windows/ in VIsual Studio 2017 is not of the latest release yet. Downloading the latest release and putting it on top of the files in VIsual Studio 2017 worked for me.
> 
> ```
> 1. download the zip file gcmw-v1.17.0.zip from https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases
> 2. navigate to C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\libexec\ (or wherever your 'missing' git-askpass.exe resides).
> 3. make a copy of the git-core folder and rename it backup or something like that
> 4. put the files from the zip file on top of the contents of your new git-core folder and overwrite where prompted
> ```
> 
> Let me know if this works for you
> 
> Edit
> 
> > might wanna use `gcmw-v1.17.1.zip` if the `1.17.0` did not work

Didn't work for me. Can you help m in this?

**Comment by sgf** [comment]
Git failed with a fatal error.
HttpRequestException encountered.
   ��������ʱ�����
HttpRequestException encountered.
   ��������ʱ�����
cannot spawn /c/app/visual studio 2019/common7/ide/commonextensions/microsoft/teamfoundation/team explorer/Git/mingw32/libexec/git-core/git-askpass.exe: No such file or directory
could not read Username for 'https://github.com': terminal prompts disabled

again and again

**Comment by mxfatih** [comment]
I had the same issue with similar symptoms.
My solution was 2 steps
- Cleaning Github Credentials in Windows Credential Manager
- SignOut and Remove all accounts in Visual Studio and Re-Sign In with github account
