### ISSUE TITLE
Unable to Authenticate with 2FA

### ISSUE THREAD

**Issue by jakevis** [github/VisualStudio#958]
Hello! Please read the contributing guidelines before submitting an issue regarding the GitHub Extension for Visual Studio.

- GitHub Extension for Visual Studio  version: 2.2.0.8
- Visual Studio version:15.1 (26403.7) - VS Enterprise 2017

__What happened__ (with steps, logs and screenshots, if possible)
When connecting to GitHub, I can validate by password but it hangs on 2FA auth. Here is the extension.log from Temp:

```
2017-04-21 14:11:41.3546|ERROR|thread: 1|SharedCache|Failed to set the UserAccount cache.
System.TypeInitializationException: The type initializer for 'NativeMethods' threw an exception. ---> System.Exception: Tried to load sqlite3.dll from C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\EXTENSIONS\VXNFUF2U.FPQ and failed miserably.
   at SQLitePCL.SQLite3Provider.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at SQLitePCL.SQLite3Provider.NativeMethods.sqlite3_open_v2(Byte[] filename, IntPtr& db, Int32 flags, Byte[] vfs)
   at SQLitePCL.SQLite3Provider.SQLitePCL.ISQLite3Provider.sqlite3_open_v2(String filename, IntPtr& db, Int32 flags, String vfs)
   at SQLitePCL.raw.sqlite3_open_v2(String filename, sqlite3& db, Int32 flags, String vfs)
   at Akavache.Sqlite3.Internal.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\SQLite.cs:line 193
   at Akavache.Sqlite3.SQLitePersistentBlobCache..ctor(String databaseFile, IScheduler scheduler) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\SqlitePersistentBlobCacheNext.cs:line 44
   at Akavache.Sqlite3.Registrations.<>c__DisplayClass0_0.<Register>b__2() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\Registrations.cs:line 34
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Akavache.Sqlite3.Registrations.<>c__DisplayClass0_0.<Register>b__3() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\Registrations.cs:line 36
   at Splat.ModernDependencyResolver.GetService(Type serviceType, String contract) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\splat\Splat\ServiceLocation.cs:line 270
   at Splat.DependencyResolverMixins.GetService[T](IDependencyResolver This, String contract) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\splat\Splat\ServiceLocation.cs:line 151
   at Akavache.BlobCache.get_UserAccount() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache\Portable\BlobCache.cs:line 87
   at GitHub.Caches.SharedCache.<>c.<.ctor>b__4_0() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.App\Caches\SharedCache.cs:line 52
   at GitHub.Caches.SharedCache.GetBlobCacheWithFallback(Func`1 blobCacheFunc, String cacheName) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.App\Caches\SharedCache.cs:line 103    at SQLitePCL.SQLite3Provider.NativeMethods.sqlite3_open_v2(Byte[] filename, IntPtr& db, Int32 flags, Byte[] vfs)
   at SQLitePCL.SQLite3Provider.SQLitePCL.ISQLite3Provider.sqlite3_open_v2(String filename, IntPtr& db, Int32 flags, String vfs)
   at SQLitePCL.raw.sqlite3_open_v2(String filename, sqlite3& db, Int32 flags, String vfs)
   at Akavache.Sqlite3.Internal.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\SQLite.cs:line 193
   at Akavache.Sqlite3.SQLitePersistentBlobCache..ctor(String databaseFile, IScheduler scheduler) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\SqlitePersistentBlobCacheNext.cs:line 44
   at Akavache.Sqlite3.Registrations.<>c__DisplayClass0_0.<Register>b__2() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\Registrations.cs:line 34
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Akavache.Sqlite3.Registrations.<>c__DisplayClass0_0.<Register>b__3() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\Registrations.cs:line 36
   at Splat.ModernDependencyResolver.GetService(Type serviceType, String contract) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\splat\Splat\ServiceLocation.cs:line 270
   at Splat.DependencyResolverMixins.GetService[T](IDependencyResolver This, String contract) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\splat\Splat\ServiceLocation.cs:line 151
   at Akavache.BlobCache.get_UserAccount() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache\Portable\BlobCache.cs:line 87
   at GitHub.Caches.SharedCache.<>c.<.ctor>b__4_0() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.App\Caches\SharedCache.cs:line 52
   at GitHub.Caches.SharedCache.GetBlobCacheWithFallback(Func`1 blobCacheFunc, String cacheName) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.App\Caches\SharedCache.cs:line 103
2017-04-21 14:11:41.3817|ERROR|thread: 1|SharedCache|Failed to set the LocalMachine cache.
System.TypeInitializationException: The type initializer for 'NativeMethods' threw an exception. ---> System.Exception: Tried to load sqlite3.dll from C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\EXTENSIONS\VXNFUF2U.FPQ and failed miserably.
   at SQLitePCL.SQLite3Provider.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at SQLitePCL.SQLite3Provider.NativeMethods.sqlite3_open_v2(Byte[] filename, IntPtr& db, Int32 flags, Byte[] vfs)
   at SQLitePCL.SQLite3Provider.SQLitePCL.ISQLite3Provider.sqlite3_open_v2(String filename, IntPtr& db, Int32 flags, String vfs)
   at SQLitePCL.raw.sqlite3_open_v2(String filename, sqlite3& db, Int32 flags, String vfs)
   at Akavache.Sqlite3.Internal.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\SQLite.cs:line 193
   at Akavache.Sqlite3.SQLitePersistentBlobCache..ctor(String databaseFile, IScheduler scheduler) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\SqlitePersistentBlobCacheNext.cs:line 44
   at Akavache.Sqlite3.Registrations.<>c__DisplayClass0_0.<Register>b__0() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\Registrations.cs:line 28
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Akavache.Sqlite3.Registrations.<>c__DisplayClass0_0.<Register>b__1() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\Registrations.cs:line 30
   at Splat.ModernDependencyResolver.GetService(Type serviceType, String contract) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\splat\Splat\ServiceLocation.cs:line 270
   at Splat.DependencyResolverMixins.GetService[T](IDependencyResolver This, String contract) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\splat\Splat\ServiceLocation.cs:line 151
   at Akavache.BlobCache.get_LocalMachine() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache\Portable\BlobCache.cs:line 65
   at GitHub.Caches.SharedCache.<>c.<.ctor>b__4_1() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.App\Caches\SharedCache.cs:line 53
   at GitHub.Caches.SharedCache.GetBlobCacheWithFallback(Func`1 blobCacheFunc, String cacheName) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.App\Caches\SharedCache.cs:line 103    at SQLitePCL.SQLite3Provider.NativeMethods.sqlite3_open_v2(Byte[] filename, IntPtr& db, Int32 flags, Byte[] vfs)
   at SQLitePCL.SQLite3Provider.SQLitePCL.ISQLite3Provider.sqlite3_open_v2(String filename, IntPtr& db, Int32 flags, String vfs)
   at SQLitePCL.raw.sqlite3_open_v2(String filename, sqlite3& db, Int32 flags, String vfs)
   at Akavache.Sqlite3.Internal.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\SQLite.cs:line 193
   at Akavache.Sqlite3.SQLitePersistentBlobCache..ctor(String databaseFile, IScheduler scheduler) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\SqlitePersistentBlobCacheNext.cs:line 44
   at Akavache.Sqlite3.Registrations.<>c__DisplayClass0_0.<Register>b__0() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\Registrations.cs:line 28
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Akavache.Sqlite3.Registrations.<>c__DisplayClass0_0.<Register>b__1() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\Registrations.cs:line 30
   at Splat.ModernDependencyResolver.GetService(Type serviceType, String contract) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\splat\Splat\ServiceLocation.cs:line 270
   at Splat.DependencyResolverMixins.GetService[T](IDependencyResolver This, String contract) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\splat\Splat\ServiceLocation.cs:line 151
   at Akavache.BlobCache.get_LocalMachine() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache\Portable\BlobCache.cs:line 65
   at GitHub.Caches.SharedCache.<>c.<.ctor>b__4_1() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.App\Caches\SharedCache.cs:line 53
   at GitHub.Caches.SharedCache.GetBlobCacheWithFallback(Func`1 blobCacheFunc, String cacheName) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.App\Caches\SharedCache.cs:line 103
2017-04-21 14:12:17.3217|ERROR|thread: 1|SqlitePersistentBlobCacheFactory|Error while creating SQLitePersistentBlobCache for C:\Users\javisser\AppData\Roaming\GitHubVisualStudio\api.github.com.cache.db. System.TypeInitializationException: The type initializer for 'NativeMethods' threw an exception. ---> System.Exception: Tried to load sqlite3.dll from C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\EXTENSIONS\VXNFUF2U.FPQ and failed miserably.
   at SQLitePCL.SQLite3Provider.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at SQLitePCL.SQLite3Provider.NativeMethods.sqlite3_open_v2(Byte[] filename, IntPtr& db, Int32 flags, Byte[] vfs)
   at SQLitePCL.SQLite3Provider.SQLitePCL.ISQLite3Provider.sqlite3_open_v2(String filename, IntPtr& db, Int32 flags, String vfs)
   at SQLitePCL.raw.sqlite3_open_v2(String filename, sqlite3& db, Int32 flags, String vfs)
   at Akavache.Sqlite3.Internal.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\SQLite.cs:line 193
   at Akavache.Sqlite3.SQLitePersistentBlobCache..ctor(String databaseFile, IScheduler scheduler) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\SqlitePersistentBlobCacheNext.cs:line 44
   at GitHub.Factories.SqlitePersistentBlobCacheFactory.CreateBlobCache(String path) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.App\Factories\SqlitePersistentBlobCacheFactory.cs:line 28
2017-04-21 14:12:18.0943|INFO|thread: 1|RepositoryHost|Log in from cache for login '(null)' to host 'https://api.github.com/' FAILED
2017-04-21 14:12:18.1031|INFO|thread: 1|RepositoryHosts|Log in to GitHub.com host 'https://api.github.com/' with username 'jakevis' FAILED
2017-04-21 14:12:56.1561|ERROR|thread: 1|SqlitePersistentBlobCacheFactory|Error while creating SQLitePersistentBlobCache for C:\Users\javisser\AppData\Roaming\GitHubVisualStudio\api.github.com.cache.db. System.TypeInitializationException: The type initializer for 'NativeMethods' threw an exception. ---> System.Exception: Tried to load sqlite3.dll from C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\EXTENSIONS\VXNFUF2U.FPQ and failed miserably.
   at SQLitePCL.SQLite3Provider.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at SQLitePCL.SQLite3Provider.NativeMethods.sqlite3_open_v2(Byte[] filename, IntPtr& db, Int32 flags, Byte[] vfs)
   at SQLitePCL.SQLite3Provider.SQLitePCL.ISQLite3Provider.sqlite3_open_v2(String filename, IntPtr& db, Int32 flags, String vfs)
   at SQLitePCL.raw.sqlite3_open_v2(String filename, sqlite3& db, Int32 flags, String vfs)
   at Akavache.Sqlite3.Internal.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\SQLite.cs:line 193
   at Akavache.Sqlite3.SQLitePersistentBlobCache..ctor(String databaseFile, IScheduler scheduler) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\akavache\Akavache.Sqlite3\SqlitePersistentBlobCacheNext.cs:line 44
   at GitHub.Factories.SqlitePersistentBlobCacheFactory.CreateBlobCache(String path) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.App\Factories\SqlitePersistentBlobCacheFactory.cs:line 28
```

**Comment by PocketMobsters** [comment]
Running into the same problem

**Comment by shana** [comment]
Interesting, thanks for the report. What version of Windows are you running?

**Comment by shana** [comment]
Also, could you double check that there is an `sqlite3.dll` file inside `C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\EXTENSIONS\VXNFUF2U.FPQ` please? Just want to rule out a bad installation of some sort there.

**Comment by PocketMobsters** [comment]
I don't have any thorough logs or anything like that to go with this brief write-up, but I can provide more info if needed when I get home from work.

I was having the same issue with 2FA hanging. Here are the steps I took for the original installation, as well as how I fixed the problem.

I'm running Windows 10 Professional, fully updated. Visual Studio 2015 Professional, fully updated as far as I know.

I was annoyed with the built-in support for GitHub and wanted to find an extension that handled it better. I did a quick google search and arrived at https://visualstudio.github.com/ . From here, I just clicked the download button and ran the installer. Didn't select anything extra, sort of just mashed the Next button when prompted.

After installation, I restarted Visual Studio 2015 and attempted to connect to my GitHub account. 2FA would hang after inputting the code and selecting "verify". I restarted Visual Studio 2015 multiple times, each time it would hang on 2FA when attempting to set up the GitHub extension.

At this point, I made my comment above and then dug around some more. One of the troubleshooting steps I found was to add the GitHub extension release feed to my Visual Studio extensions manager. Under the Online section, in my GitHub feed, every release had a green checkmark next to it, and I had no options to switch versions or even to see which version I had installed. The troubleshooting guide I found mentioned that you could easily switch versions here without having to do anything more than adding the feed and have the extension installed.

I decided to do a full uninstall of the GitHub extension and installed the latest version from the extensions manager feed I set up for GitHub. I restarted Visual Studio 2015 and and it worked just fine and I've had 0 issues with the extension since then

I apologize for not having any logs to dump here, as well as for not having any additional information.

If need be, I can provide any additionally requested information when I get home from work tonight, but I saw you responding to this issue and figured I'd clarify from my earlier comment above.

I'm not sure why the reinstall worked, could have been any number of reasons, but the new/updated extension (v2) handles the login process SIGNIFICANTLY differently than the original version I had installed (v1). V1 had the login screen open in a new window, whereas V2 was handling the login screen INSIDE of the Team Explorer toolbox pane. I'm fairly certain, due to this, that the top result on Google, the link I posted above, is installing an outdated version of GitHub. Either that or I'm dumb and stupid and messed up somewhere.

**Comment by grokys** [comment]
Glad a reinstall solved it, @PocketMobsters. @jakevis does uninstalling and reinstalling fix the problem for you?

@shana regarding the login dialog hanging on 2FA, that _should_ be fixed by #845.

**Comment by paladique** [comment]
Also, @PocketMobsters could you confirm the version you installed that worked? The version should be in Extensions and Updates.

**Comment by jakevis** [comment]
@shana sorry for the slow response - looking in my install dir I am missing that dll.. I only have SQLitePCL.raw.dll

On both the machines with this issue, both are running win 10 enterprise. I will note one is an "insider preview", the other is just a fully patched regular machine.

I will try a re-install of the plugin now.

**Comment by jakevis** [comment]
@grokys yep - a reinstall fixed it. Interestly there still isnt an sqlite3.dll in the install dir.

But none the less its working. Ill try again on the work PC Monday. Thanks again.

**Comment by shana** [comment]
Closing this one as it seems to be fixed (at least the horrible sqlite crash). If this happens again, please reopen.
